apiVersion: ae.dev/v1alpha1
kind: Deployment
metadata:
  name: echo-mc
spec:
  image: ghcr.io/ae/demo-echo:latest
  replicas: 1
  ports:
    - name: http
      containerPort: 8080
  health:
    readiness:
      httpGet:
        path: /ready
        port: 8080
  containers:
    - name: metrics
      image: busybox:1.36
      command: ["sh", "-c"]
      args: ["while true; do echo metrics:1; sleep 10; done"]
      projectionMounts:
        - path: config
          mountPath: /etc/app-config
  initContainers:
    - name: init-wait
      image: busybox:1.36
      command: ["sh", "-c", "echo init ok"]
