apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: demo
  labels:
    app: echo
data: null
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo
  template:
    metadata:
      labels:
        app: echo
    spec:
      containers:
      - name: echo
        image: demo-blue:latest
        env:
        - name: APP_NAME
          value: echo
        - name: MESSAGE
          value: Hello from echo
        - name: APP_MODE
          value: demo-override
        - name: APP_MODE
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: mode
        - name: APP_COLOR
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: color
        - name: API_TOKEN
          valueFrom:
            secretKeyRef:
              name: demo-secret
              key: token
        ports:
        - name: http
          containerPort: 8080
        securityContext:
          runAsNonRoot: true
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        readinessProbe:
          initialDelaySeconds: 1
          timeoutSeconds: 1
          periodSeconds: 5
          successThreshold: 1
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 8080
        livenessProbe:
          initialDelaySeconds: 3
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 8080
      terminationGracePeriodSeconds: 10
      serviceAccountName: app-sa
---
apiVersion: v1
kind: Service
metadata:
  name: echo
  namespace: demo
spec:
  selector:
    app: echo
  ports:
  - name: http
    port: 80
    targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: echo
  namespace: demo
spec:
  rules:
  - host: echo.home.arpa
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: echo
            port:
              number: 80
  ingressClassName: traefik
  tls:
  - hosts:
    - echo.home.arpa
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-sa
  namespace: demo
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: echo
  namespace: demo
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: echo
  minReplicas: 2
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
