apiVersion: ae.dev/v1alpha1
kind: Deployment
metadata:
  name: ha-edge-web-smoke
spec:
  image: docker.io/library/demo-shell:latest
  replicas: 1
  ports:
    - name: http
      containerPort: 8080
  nodeSelector:
    role: worker
    site: sea
  health:
    readiness:
      httpGet:
        path: /healthz
        port: 8080
      initialDelaySeconds: 1
      timeoutSeconds: 2
      periodSeconds: 2
      successThreshold: 1
      failureThreshold: 5
    liveness:
      httpGet:
        path: /healthz
        port: 8080
      initialDelaySeconds: 5
      timeoutSeconds: 1
      periodSeconds: 10
      successThreshold: 1
      failureThreshold: 3
  ingress:
    host: ha-edge-web-smoke.home.arpa
    path: /
