{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "k1s-edge-gateway.pvcName" . }}
  labels:
    {{- include "k1s-edge-gateway.labels" . | nindent 4 }}
    app.kubernetes.io/component: edge-gateway
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  volumeMode: Filesystem
  {{- if .Values.persistence.storageClassName }}
  storageClassName: {{ .Values.persistence.storageClassName | quote }}
  {{- end }}
{{- end }}
