apiVersion: ae.dev/v1alpha1
kind: App
metadata:
  name: echo
spec:
  image: mendhak/http-https-echo:37
  replicas: 1
  env:
    - name: APP_NAME
      value: echo
    - name: MESSAGE
      value: "Hello from echo"
    - name: APP_MODE
      value: demo-override
  ports:
    - name: http
      containerPort: 8080
  service:
    port: 18090
    targetPort: 8080
  health:
    readiness:
      httpGet:
        path: /healthz
        port: 8080
      initialDelaySeconds: 1
      timeoutSeconds: 1
      periodSeconds: 5
      successThreshold: 1
      failureThreshold: 3
    liveness:
      httpGet:
        path: /healthz
        port: 8080
      initialDelaySeconds: 3
      timeoutSeconds: 1
      periodSeconds: 10
      successThreshold: 1
      failureThreshold: 3
  secretRefs:
    - name: demo-secret
      path: specs/examples/demo-secret.sops.yaml
      env:
        - name: API_TOKEN
          key: token
      files:
        - key: token
          file: secret/token
  configRefs:
    - name: app-config
      path: configs/app-config.yaml
      env:
        - name: APP_MODE
          key: mode
        - name: APP_COLOR
          key: color
      files:
        - key: mode
          file: config/app_mode.txt
  ingress:
    host: echo.home.arpa
    path: /
  resources:
    requests:
      cpu: 0.05
      memory: 128Mi
