apiVersion: ae.dev/v1alpha1
kind: App
metadata:
  name: echo-mr
spec:
  image: demo-blue:latest
  replicas: 3
  ports:
    - name: http
      containerPort: 8080
  health:
    readiness:
      httpGet: { path: "/", port: 8080 }
      initialDelaySeconds: 2
      timeoutSeconds: 1
      periodSeconds: 5
  ingress:
    host: echo-mr.home.arpa
    path: /
  resources:
    requests:
      cpu: 0.1
      memory: 128Mi
