apiVersion: ae.dev/v1alpha1
kind: Deployment
metadata:
  name: echo-mr
spec:
  image: mendhak/http-https-echo:37
  replicas: 3
  ports:
    - name: http
      containerPort: 8080
  health:
    readiness:
      httpGet: { path: "/", port: 8080 }
      initialDelaySeconds: 2
      timeoutSeconds: 1
      periodSeconds: 5
    liveness:
      httpGet: { path: "/", port: 8080 }
      initialDelaySeconds: 5
      timeoutSeconds: 1
      periodSeconds: 10
      failureThreshold: 3
    startup:
      httpGet: { path: "/", port: 8080 }
      failureThreshold: 30
      periodSeconds: 5
  ingress:
    host: echo-mr.home.arpa
    path: /
  resources:
    requests:
      cpu: 0.1
      memory: 128Mi
  security:
    runAsUser: 1000
    readOnlyRootFilesystem: true
    dropCapabilities: ["NET_RAW"]
    seccompProfileType: RuntimeDefault
  topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: kubernetes.io/hostname
      whenUnsatisfiable: ScheduleAnyway
      labelSelector:
        matchLabels:
          app: echo-mr
  networkPolicy:
    policyTypes: ["Ingress", "Egress"]
    ingress:
      - {}
    egress:
      - {}
  exportHints:
    emitPDB: true
    suppressImageMultiArchWarning: true
