apiVersion: ae.dev/v1alpha1
kind: Deployment
metadata:
  name: web-preset-pvc
spec:
  image: mendhak/http-https-echo:37
  replicas: 2
  ports:
    - name: http
      containerPort: 8080
  ingress:
    host: web-preset-pvc.home.arpa
    path: /
  storage:
    - name: data
      mountPath: /data
      size: 2Gi
