#!/usr/bin/env bash
set -euo pipefail

# Simple end-to-end smoke test for the multi-port example.
# Prereqs: init_demo.sh, Docker/Podman, sops. Uses default Caddy HTTPS port 8443 unless overridden.

ROOT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/../.." &>/dev/null && pwd)
cd "$ROOT_DIR"

export CADDY_HTTPS_PORT="${CADDY_HTTPS_PORT:-8443}"

caddy_https_status() {
  curl -ksS \
    --resolve "echo-multi.home.arpa:${CADDY_HTTPS_PORT}:127.0.0.1" \
    -o /dev/null \
    -w '%{http_code}' \
    "https://echo-multi.home.arpa:${CADDY_HTTPS_PORT}/" || true
}

reload_caddy_config() {
  local cli="${AE_CONTAINER_CLI:-docker}"
  local container="${AE_CADDY_CONTAINER:-dev-caddy-1}"
  if ! command -v "$cli" >/dev/null 2>&1; then
    return 1
  fi
  if ! "$cli" ps -a --format '{{.Names}}' 2>/dev/null | grep -qx "$container"; then
    return 1
  fi
  "$cli" exec "$container" caddy reload --config /etc/caddy/Caddyfile >/dev/null 2>&1
}

if [[ "$(id -u)" -ne 0 ]] && ! sudo -n true >/dev/null 2>&1; then
  echo "[e2e] ERROR: demo e2e requires root or cached sudo on this host."
  echo "[e2e] run 'sudo -v' first or rerun with: sudo -E make e2e"
  exit 1
fi

echo "[e2e] Starting demo with multi-port example"
./scripts/init_demo.sh --demo-echo-multi -y

if [[ ! -s state/env.sh ]]; then
  echo "[e2e] ERROR: state/env.sh was not generated by init_demo"
  exit 1
fi

# shellcheck disable=SC1091
. state/env.sh

echo "[e2e] Checking controller status for echo-multi"
python -m ae.cli status echo-multi --wide || true

if ! python -m ae.cli status echo-multi --watch 2 --timeout 90; then
  echo "[e2e] ERROR: echo-multi not ready"
  python -m ae.cli status echo-multi --wide || true
  exit 1
fi

echo "[e2e] Curling ingress at https://echo-multi.home.arpa:${CADDY_HTTPS_PORT}/"
code="$(caddy_https_status)"
if [[ "$code" != "200" && "$code" != "404" ]]; then
  echo "[e2e] ingress returned ${code}; reloading Caddy and retrying"
  reload_caddy_config || true
  for _ in {1..10}; do
    sleep 2
    code="$(caddy_https_status)"
    if [[ "$code" == "200" || "$code" == "404" ]]; then
      break
    fi
  done
fi
if [[ "$code" != "200" && "$code" != "404" ]]; then
  echo "[e2e] ERROR: unexpected HTTP status: $code"
  exit 1
fi

echo "[e2e] OK: multi-port E2E passed (status=$code)"
