repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.6.5
    hooks:
      - id: ruff
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.0
    hooks:
      - id: mypy
        additional_dependencies:
          - pydantic>=2.9
          - PyYAML>=6.0
  - repo: local
    hooks:
      - id: versioning
        name: versioning
        entry: python scripts/check_versioning.py
        language: system
        pass_filenames: false
        files: ^(pyproject\.toml|CHANGELOG\.md)$
      - id: pytest
        name: pytest
        entry: pytest
        language: system
        pass_filenames: false
        types: [python]
