apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "k1s-core-ha.controllerName" . }}
  labels:
    {{- include "k1s-core-ha.labels" . | nindent 4 }}
automountServiceAccountToken: false
---
{{- if .Values.apishim.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "k1s-core-ha.apishimName" . }}
  labels:
    {{- include "k1s-core-ha.labels" . | nindent 4 }}
automountServiceAccountToken: false
{{- end }}
