global:
  registryHost: reg.microk8s.core.home.arpa:32000

stack:
  name: k1s-dev-a
  domain: k1s-dev-a.core.home.arpa

controller:
  replicas: 3
  runtimeHostSocketPath: /var/snap/microk8s/common/run/containerd.sock
  securityContext:
    runAsUser: 10001
    runAsGroup: 1005
    runAsNonRoot: true
    allowPrivilegeEscalation: false
  siteIds:
    - host-a
    - host-b
    - workerbee-edge
  routeBundles:
    enabled: true
    intervalSeconds: 5
    replayIntervalSeconds: 30
  api:
    mutationsEnabled: true
    adminTokenSecretKey: apishim-admin-token
    readTokenSecretKey: apishim-read-token
    dashboardBootstrapTokenSecretKey: apishim-admin-token
  persistence:
    enabled: true
    storageClassName: microk8s-hostpath
    size: 5Gi
  image:
    repository: k1s/k1s-core
    tag: dev

apishim:
  enabled: true
  image:
    repository: k1s/k1s-apishim
    tag: dev

etcd:
  storageClassName: microk8s-hostpath
  storageSize: 5Gi

nats:
  storageClassName: microk8s-hostpath
  storageSize: 5Gi

natsExporter:
  image:
    repository: docker.io/natsio/prometheus-nats-exporter
    tag: 0.19.2

edgeProxy:
  ratholeImage:
    repository: k1s/k1s-rathole
    tag: dev

bootstrap:
  controller:
    hostOverride: 192.168.29.15
  natsLeaf:
    hostOverride: 192.168.29.15
  rathole:
    hostOverride: 192.168.29.15

ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
  tls:
    enabled: true
    secretName: k1s-dev-a-ingress-tls
    certificate:
      create: true
      issuerRef:
        name: org-ca
        kind: ClusterIssuer

serviceMonitor:
  enabled: true
  additionalLabels:
    release: kube-prometheus-stack

prometheusRule:
  enabled: true
  additionalLabels:
    release: kube-prometheus-stack
