"""Fabric roadmap support contracts."""

from ae.fabric.symbolic import (
    SYMBOLIC_ADVISORY_DECISION_API_VERSION,
    SYMBOLIC_ADVISORY_DECISION_REQUIRED_FIELDS,
    SYMBOLIC_ADVISOR_SCENARIO_EVAL_API_VERSION,
    SYMBOLIC_ADVISOR_SCENARIO_EVAL_REQUIRED_FIELDS,
    SYMBOLIC_ADVISOR_SCENARIO_RESULT_REQUIRED_FIELDS,
    SYMBOLIC_FACT_NAMESPACE,
    SYMBOLIC_FACT_SOURCE_WORKERBEE_AI_FABRIC,
    SYMBOLIC_RELATIONSHIP_PREDICATES,
)

__all__ = [
    "SYMBOLIC_ADVISORY_DECISION_API_VERSION",
    "SYMBOLIC_ADVISORY_DECISION_REQUIRED_FIELDS",
    "SYMBOLIC_ADVISOR_SCENARIO_EVAL_API_VERSION",
    "SYMBOLIC_ADVISOR_SCENARIO_EVAL_REQUIRED_FIELDS",
    "SYMBOLIC_ADVISOR_SCENARIO_RESULT_REQUIRED_FIELDS",
    "SYMBOLIC_FACT_NAMESPACE",
    "SYMBOLIC_FACT_SOURCE_WORKERBEE_AI_FABRIC",
    "SYMBOLIC_RELATIONSHIP_PREDICATES",
]
