#!/usr/bin/env bash
set -e

# Unset common k1s/ae environment variables that leak between profiles.
unset \
  AE_API_SERVER \
  AE_APISHIM_SERVER \
  AE_STATE_DB \
  AE_STATE_BACKEND \
  AE_ETCD_ENDPOINTS \
  AE_ETCD_PREFIX \
  AE_PROJECTION_ROOT \
  AE_SPECS_DIR \
  AE_APISHIM_DB \
  AE_APISHIM_RUNTIME \
  AE_APISHIM_MIRROR \
  AE_APISHIM_SOT \
  AE_APISHIM_TOKEN \
  AE_APISHIM_READ_TOKEN \
  AE_APISHIM_SESSION_SECRET \
  AE_APISHIM_EXEC_TOKEN \
  AE_APISHIM_PORTFORWARD_TOKEN \
  AE_API_ADMIN_TOKEN \
  AE_API_SCALER_TOKEN \
  AE_API_READ_TOKEN \
  AE_API_MUTATIONS \
  AE_LABS_TOKEN \
  AE_LABS_HELM_TOKEN \
  AE_LABS_HELM_SERVER \
  AE_CADDY_SITES \
  AE_CADDY_FILE \
  AE_CADDY_CONTAINER \
  AE_CONTAINER_CLI \
  AE_DOCKER_NETWORK \
  AE_PODMAN_NETWORK

echo "[ae-env-clear] cleared AE_* profile/auth variables from this shell"
