#!/usr/bin/env python3
"""Render ops/dev/haproxy/haproxy.cfg from controller API /system for an app.

Usage:
  scripts/dev/update_haproxy_from_api.py --app tcp-echo [--server http://127.0.0.1:9108] \
      [--cfg ops/dev/haproxy/haproxy.cfg] [--port 9000]

Respects AE_API_READ_TOKEN for bearer auth if the API is protected.
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path
from urllib.request import Request, urlopen


def _get_json(url: str, token: str | None = None) -> dict:
    req = Request(url, headers={"Accept": "application/json"})
    if token:
        req.add_header("Authorization", f"Bearer {token}")
    with urlopen(req, timeout=10) as resp:  # nosec - local dev use
        body = resp.read().decode("utf-8")
        try:
            return json.loads(body)
        except json.JSONDecodeError:
            raise RuntimeError(f"API {url} did not return JSON")


def _haproxy_cfg(public_port: int, servers: list[tuple[str, int]]) -> str:
    lines = [
        "# generated by scripts/dev/update_haproxy_from_api.py",
        "global",
        "  maxconn 1024",
        "",
        "defaults",
        "  mode tcp",
        "  timeout connect 5s",
        "  timeout client  30s",
        "  timeout server  30s",
        "",
        "frontend tcp_app",
        f"  bind *:{public_port}",
        "  default_backend app_be",
        "",
        "backend app_be",
        "  balance roundrobin",
    ]
    if not servers:
        lines.append("  # no servers discovered; write after app is running")
    else:
        for i, (_name, hp) in enumerate(servers, start=1):
            lines.append(f"  server r{i} 127.0.0.1:{int(hp)} check")
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--server", default=os.getenv("AE_API_SERVER", "http://127.0.0.1:9108"))
    p.add_argument("--app", required=True)
    p.add_argument("--cfg", default="ops/dev/haproxy/haproxy.cfg")
    p.add_argument("--port", type=int, default=int(os.getenv("HAPROXY_TCP_PORT", "9000")))
    p.add_argument("--dry-run", action="store_true")
    args = p.parse_args(argv)

    base = str(args.server).rstrip("/")
    token = os.getenv("AE_API_READ_TOKEN") or None

    sysinfo = _get_json(base + "/system", token)
    containers = list(sysinfo.get("containers") or [])
    host_ports: list[int] = []
    for c in containers:
        labels = c.get("labels") or {}
        if (
            labels.get("ae.app") or labels.get("ae.app_name") or labels.get("ae.app-name")
        ) == args.app:
            for hp in c.get("host_ports") or []:
                try:
                    host_ports.append(int(hp))
                except Exception:
                    continue
    host_ports = sorted(set(host_ports))
    servers = [(f"{args.app}", p) for p in host_ports]

    cfg_text = _haproxy_cfg(int(args.port), servers)
    if args.dry_run:
        sys.stdout.write(cfg_text)
        return 0
    path = Path(args.cfg)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(cfg_text, encoding="utf-8")
    print(f"wrote {path} with {len(servers)} server(s)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
# ruff: noqa
