#!/usr/bin/env python3
"""Watch controller /system and keep HAProxy config in sync for an app.

On changes to the discovered host ports for the target app's replicas, this
script rewrites ops/dev/haproxy/haproxy.cfg and restarts the dev HAProxy service.

Usage:
  scripts/dev/watch_haproxy.py --app tcp-echo \
      [--server http://127.0.0.1:9108] \
      [--cfg ops/dev/haproxy/haproxy.cfg] \
      [--port 9000] \
      [--compose ops/dev/docker-compose.yaml] \
      [--service haproxy] \
      [--interval 5]

Notes:
- Honors AE_API_READ_TOKEN for bearer auth if the API is protected.
- Requires Docker and docker compose available on PATH for restarts.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import subprocess
import sys
import time
from pathlib import Path
from urllib.request import Request, urlopen


def _get_json(url: str, token: str | None = None) -> dict:
    req = Request(url, headers={"Accept": "application/json"})
    if token:
        req.add_header("Authorization", f"Bearer {token}")
    with urlopen(req, timeout=10) as resp:  # nosec - local dev use
        body = resp.read().decode("utf-8")
        try:
            return json.loads(body)
        except json.JSONDecodeError:
            raise RuntimeError(f"API {url} did not return JSON")


def _haproxy_cfg(public_port: int, servers: list[tuple[str, int]]) -> str:
    lines = [
        "# generated by scripts/dev/watch_haproxy.py",
        "global",
        "  maxconn 1024",
        "",
        "defaults",
        "  mode tcp",
        "  timeout connect 5s",
        "  timeout client  30s",
        "  timeout server  30s",
        "",
        "frontend tcp_app",
        f"  bind *:{public_port}",
        "  default_backend app_be",
        "",
        "backend app_be",
        "  balance roundrobin",
    ]
    if not servers:
        lines.append("  # no servers discovered; write after app is running")
    else:
        for i, (_name, hp) in enumerate(servers, start=1):
            lines.append(f"  server r{i} 127.0.0.1:{int(hp)} check")
    return "\n".join(lines) + "\n"


def _restart_haproxy(compose_bin: str, compose_file: str, service: str) -> None:
    cmd = [compose_bin, "compose", "-f", compose_file, "restart", service]
    try:
        subprocess.run(cmd, check=True)  # nosec - dev tooling
    except Exception as exc:  # noqa: BLE001
        print(f"[watch] restart failed: {exc}", file=sys.stderr)


def _validate_haproxy(
    compose_bin: str, compose_file: str, service: str, cfg_in_container: str
) -> bool:
    """Return True if haproxy -c -f <cfg> inside the service container succeeds."""
    cmd = [
        compose_bin,
        "compose",
        "-f",
        compose_file,
        "exec",
        "-T",
        service,
        "haproxy",
        "-c",
        "-f",
        cfg_in_container,
    ]
    try:
        proc = subprocess.run(cmd, check=False, capture_output=True, text=True)  # nosec - dev tooling
        if proc.returncode == 0:
            return True
        sys.stderr.write(
            f"[watch] haproxy -c failed (rc={proc.returncode}):\n{proc.stdout or proc.stderr}\n"
        )
        return False
    except Exception as exc:  # noqa: BLE001
        print(f"[watch] validation failed to execute: {exc}", file=sys.stderr)
        return False


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--server", default=os.getenv("AE_API_SERVER", "http://127.0.0.1:9108"))
    p.add_argument("--app", required=True)
    p.add_argument("--cfg", default="ops/dev/haproxy/haproxy.cfg")
    p.add_argument("--port", type=int, default=int(os.getenv("HAPROXY_TCP_PORT", "9000")))
    p.add_argument("--compose", default="ops/dev/docker-compose.yaml")
    p.add_argument("--service", default="haproxy")
    p.add_argument("--interval", type=float, default=5.0)
    p.add_argument(
        "--compose-bin",
        default=os.getenv("COMPOSE_BIN", "docker"),
        help="compose binary to use (docker or podman)",
    )
    args = p.parse_args(argv)

    base = str(args.server).rstrip("/")
    token = os.getenv("AE_API_READ_TOKEN") or None
    cfg_path = Path(args.cfg)
    cfg_path.parent.mkdir(parents=True, exist_ok=True)

    last_sig = ""
    last_text = ""
    print(
        f"[watch] tracking app={args.app} port={args.port} api={base} cfg={cfg_path} compose={args.compose}:{args.service} interval={args.interval}s"
    )
    while True:
        try:
            sysinfo = _get_json(base + "/system", token)
            containers = list(sysinfo.get("containers") or [])
            host_ports: list[int] = []
            for c in containers:
                labels = c.get("labels") or {}
                if (
                    labels.get("ae.app") or labels.get("ae.app_name") or labels.get("ae.app-name")
                ) == args.app:
                    for hp in c.get("host_ports") or []:
                        try:
                            host_ports.append(int(hp))
                        except Exception:
                            continue
            host_ports = sorted(set(host_ports))
            servers = [(args.app, p) for p in host_ports]
            cfg_text = _haproxy_cfg(int(args.port), servers)
            sig = hashlib.sha256(cfg_text.encode("utf-8")).hexdigest()
            if sig != last_sig:
                prev_text = cfg_path.read_text(encoding="utf-8") if cfg_path.exists() else ""
                cfg_path.write_text(cfg_text, encoding="utf-8")
                # Validate inside the container before restart
                ok = _validate_haproxy(
                    args.compose_bin,
                    args.compose,
                    args.service,
                    "/usr/local/etc/haproxy/haproxy.cfg",
                )
                if ok:
                    print(
                        f"[watch] wrote {cfg_path} with {len(servers)} server(s); restarting {args.service}"
                    )
                    _restart_haproxy(args.compose_bin, args.compose, args.service)
                    last_sig = sig
                    last_text = cfg_text
                else:
                    # revert to previous config if we had one
                    if prev_text:
                        cfg_path.write_text(prev_text, encoding="utf-8")
                        print(
                            "[watch] reverted haproxy.cfg due to validation failure",
                            file=sys.stderr,
                        )
                    else:
                        print(
                            "[watch] keeping generated config despite validation failure (no previous file to restore)",
                            file=sys.stderr,
                        )
        except Exception as exc:  # noqa: BLE001
            print(f"[watch] warning: {exc}", file=sys.stderr)
        try:
            time.sleep(float(args.interval))
        except KeyboardInterrupt:
            break
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
